

@startuml
title 实现资源限制-01

skinparam sequence {

    ActorBorderColor black
    LifeLineBorderColor black

    ParticipantBorderColor black
}


actor user
participant mydocker
participant RunCommand
participant Run
participant cgroups
participant InitCommand
participant Init


user -> mydocker : 1. mydocker run -it -m 5M /bin/sh
activate mydocker
mydocker -> RunCommand: 2. 解析参数
activate RunCommand
RunCommand -> Run: 3. 创建namespace隔离容器进程
activate Run
Run -> cgroups: 4. 调用Set,Apply设置好内存限制
activate cgroups
cgroups --> Run: 5. 返回
deactivate cgroups

Run --> RunCommand: 6. 返回配置好隔离参数\n以及内存限制的进程
deactivate Run
deactivate RunCommand
RunCommand --> mydocker: 7. 返回容器进程
deactivate mydocker
mydocker -> mydocker: 8. 容器内进程调用自己\n/proc/self/exe init /bin/sh
mydocker -> InitCommand: 9. 解析参数
activate InitCommand
InitCommand -> Init: 10. 初始化容器,挂载proc文件\n运行用户指定程序
activate Init
Init --> InitCommand: 11. 创建完成,容器开始运行
deactivate Init
InitCommand --> user: 12. 创建完成,容器开始运行
deactivate InitCommand

@enduml