

@startuml
title 实现列出所有运行容器

skinparam sequence {

    ActorBorderColor black
    LifeLineBorderColor black
    ActorBackgroundColor #87CEFA


    ParticipantBorderColor black
    ParticipantBackgroundColor #FFE4E1
}


actor user
participant mydocker
participant LogCommand
participant Log


user -> mydocker : 1. mydocker logs 容器名
activate mydocker
mydocker -> LogCommand: 2. 解析参数
activate LogCommand
LogCommand -> Log: 3. 发请求
activate Log
Log --> LogCommand: 4. 找到该容器日志
deactivate Log
LogCommand --> mydocker: 5. 返回
deactivate LogCommand
mydocker --> user: 6. 打印该容器日志
deactivate mydocker

@enduml
